// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product_info.proto

package ru.voroby.grpc.protos;

public interface ProductIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:commerce.ProductID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
