// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product_info.proto

package ru.voroby.grpc.protos;

public final class ProductInfoProto {
  private ProductInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commerce_ProductID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_commerce_ProductID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_commerce_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_commerce_Product_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022product_info.proto\022\010commerce\"\032\n\tProduc" +
      "tID\022\r\n\005value\030\001 \001(\t\"G\n\007Product\022\n\n\002id\030\001 \001(" +
      "\t\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\r\n\005" +
      "price\030\004 \001(\0022y\n\013ProductInfo\0224\n\naddProduct" +
      "\022\021.commerce.Product\032\023.commerce.ProductID" +
      "\0224\n\ngetProduct\022\023.commerce.ProductID\032\021.co" +
      "mmerce.ProductB+\n\025ru.voroby.grpc.protosB" +
      "\020ProductInfoProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_commerce_ProductID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_commerce_ProductID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_commerce_ProductID_descriptor,
        new String[] { "Value", });
    internal_static_commerce_Product_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_commerce_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_commerce_Product_descriptor,
        new String[] { "Id", "Name", "Description", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
